name: upstash_redis
description: upstash/redis is an HTTP/REST based Redis client for dart, built on top of Upstash REST API.
version: 2.0.0
homepage: https://github.com/rebaz94/upstash-redis

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  http: ^1.1.0
  collection: ^1.18.0

dev_dependencies:
  lints: ^2.1.1
  test: ^1.24.7
  crypto: ^3.0.3
