name: upstash_redis
description: upstash/redis is an HTTP/REST based Redis client for dart, built on top of Upstash REST API.
version: 1.0.5+1
homepage: https://github.com/rebaz94/upstash-redis

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.5
  collection: ^1.16.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.4
